services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_DATABASE=gamedb
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123
    networks:
      - sqlNetwork
    ports:
      - "3307:3306"  
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql  # Persistent storage for MySQL
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Initializes schema on first run
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql # add characters

  api:
    container_name: backend_api
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - sqlNetwork
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=pass123
      - DB_NAME=gamedb
      - DB_PORT=3306
      - SECRET_KEY=BANANA_STAND

  client:
    container_name: frontend_client
    restart: on-failure
    build:
      context: ./client
    ports:
      - "3001:3000"
    networks:
      - sqlNetwork
    depends_on:
      api:
        condition: service_started

networks:
  sqlNetwork:
    driver: bridge

volumes:
  db_data:
    driver: local  # Persistent MySQL data